### PR TITLE
Fix Export Form

### PR DESCRIPTION
**Pull request by dauglyon**
fixes three punchlist bugs:

- `Don’t show read-only narratives in the export select box`
- `Export form needs improved error states`
- `In export GUI, Data Object Name -> New [Genome | Assembly] Set Object Name`

also fixes input blur/focus handler forwarding and disables the export button in the select modal when there is no selection.

#### Success
Screenshot 2024-03-11 at 3 20 52 PM

#### Validation Error
Screenshot 2024-03-11 at 4 06 14 PM

#### Server Error (forced this error because I couldn't figure out a valid form state that lead to a server error)
Screenshot 2024-03-11 at 3 29 49 PM

### CODE REVIEW

**Review by codytodonnell — APPROVED** [review]
This all looks good. The only issue I'm seeing locally is that the scrollbar bugs out in the modal while the match is processing. I'm not sure if this is related to a change you made or not. I could merge your changes into the modal cleanup branch though and handle the issue there.

I also don't have any read-only narratives so I can't confirm that feature. However I am not seeing any narratives in the export menu which could be a good sign.

**Comment by dauglyon** [comment]
During a match or during export? I only changed the export modal so I'm assuming the latter? Can you screencap and share?

**Comment by dauglyon** [comment]
Also just realized I committed with my error image code changes still there ("badtype")

**Comment by codytodonnell** [comment]
> During a match or during export? I only changed the export modal so I'm assuming the latter? Can you screencap and share?

Screenshot 2024-03-11 at 5 13 02 PM

It's in the match modal. The scrollbar expands and detracts while loading

**Comment by dauglyon** [comment]
Hmm yeah, shouldn't be this branch which is causing that. Is main different for you? I can't reproduce

**Comment by codytodonnell** [comment]
I'm seeing it on other branches too so it must be coming from somewhere else.

**Pull request merged**
